### PR TITLE
WIP: Improvement/graphql

### PR DESCRIPTION
**Pull request by lappalj4**
Implementing GraphQL in the app (not yet complete, but in working condition). First phase will be to fully implement it in some low-hanging fruits, such as just the queries on the public pages, and then we can see how to best use it elsewhere. 

Current features: 

- Implemented complete schemas for UserProfile, Event, Registration
- Events on the frontpage and event detail page are queried with GraphQL
- User profile in UserMenu is queried with GraphQL
- Registrations on Account dashboard are queried with GraphQL
- Replaced everything in redux/eventdetail with GraphQL (Event detail page and Registration form). 

Miscellaneous stuff this branch also includes:

- Setup for running database migrations under `backend/migrations`
- The first such migration for changing event.userDetailsConfig into a slightly more sensible format (which works better with GraphQL)
- A rework of the Admin UI for editing registration questions in the organiser dashboard

TODO before release:
- Replace everything in redux/account with GraphQL (Essentially querying full profile and updating profile details with mutation)

In the meantime, feel free to check it out and see how it currently works! Relevant files can be found in:

- frontend/src/graphql/*
- backend/modules/xxx/graphql.js & backend/modules/xxx/graphql-controller.js
- backend/modules/graphql.js
- backend/modules/graphql-controller-factory.js

### CODE REVIEW

**Comment by lappalj4** [comment]
@Earlo almost done now, I'll see if I can finish the account page migration as well this week. It's not necessarily a blocker if I can't make it happen, but would be nice to close out the features I started working on. I think you should take some time to look through the diff to a) understand what I've done and ask any questions you have, and b) See if you can spot any errors or bugs, especially related to access-control 

The behaviour for all features should remain unchanged with this PR.

**Comment by lappalj4** [comment]
Also @biharygergo if you're interested and have time, feel free to look through this branch as well. I think in the long term (read: quite short term) we'll be refactoring more and more features to GraphQL and implementing most new ones with it as well.

**Comment by lappalj4** [comment]
General note: there are some slightly hacky solutions in there as well, which were necessary due to our data model being rather dynamic with regards to the UserProfile and Registration models. Let me know if something doesn't make sense and I'll try to clarify!

**Comment by lappalj4** [comment]
@Earlo Okay, I think it would be a good idea to get this tested and merged as soon as possible, so that we can start implementing other features on top of GraphQL and merging some of the other PRs. 

I didn't yet implement the account editing under /account/profile with GraphQL but that can be done later, it's not a big deal. This PR contains quite a few changes, so we should test at least the following cases before merging: 

- On a fresh database: try creating a user, creating an event, editing said event, registering to the event. Make sure all of this still works (I've tested it but could have missed some edge case). Everything that happens after the registration form has been submitted (e.g. event dashboard) has been left unchanged. 
- Do the same on your local with a clone of the dev database (and dev environment variables)
- Do the same on your local with a clone of the prod database (and prod environment variables)

As mentioned, let me know if any help or clarification is needed.

**Comment by biharygergo** [comment]
I'm in general a bit skeptical about introducing such a big change to the project at this stage. I believe it might be better to make things and functionality solid and trusty first, before refactoring things that are already working well.

I have not yet looked through this branch yet, so it might be completely fine, but I still feel that this might introduce unnecessary complexity to the platform and increase the learning curve for other contributors significantly.

What do you think?

**Comment by Earlo** [comment]
@biharygergo  I agree that those are valid concerns. However the current platform architecture has a lot of compromises made to meet the deadline of 2019 main event. Doing some heavy refactoring now makes sure that we don't need to start building a new platform from scrap in two years.

**Comment by lappalj4** [comment]
@biharygergo thanks for the comments - I hear you. I would usually agree, but there's a few key reasons why I think this is a beneficial update:

1) It's purely additional - none of the "old" REST functionality has been removed and could still be used just as well - GraphQL is just another tool which is useful for some (fairly many) situations. GraphQL can be used where it makes your life as a developer easier, but I've already ran into some situations where REST just makes more sense, so then it's appropriate to use that.

2) As @Earlo mentioned, and as I think you'll agree, a lot of the functionality needs to be looked at again and redone anyway, so imo it's a good opportunity to introduce gql at the same time. While working on this branch I've ran into several quite obvious bugs/flaws in my own code I've written back when I started working on this project last spring, and also into many situations where implementing something again in gql was just so much simpler from an architecture standpoint.

I personally think it'll be much easier to fix some of the big issues in the app with the help of this new tool :)

**Pull request merged**
