### PR TITLE
Feature/emails tab

### PR DESCRIPTION
**Pull request by davidamebley**
Added a new `Emails` tab that allows generic email customization for the `Acceptance Email`, `Rejection Email`, and `Registration Email` emails including their `subject`, `subtitle`, and `body` fields, as well as setting the 'from' email and name fields

### CODE REVIEW

**Comment by samurotko** [comment]
@davidamebley Great work overall! There are however few small issues. Fix those in new PR.

- [ ] event times are wrong. seem to be UTC, not taking timezone into a count, in some cases, and in some cases current time. In my test {SUBMISSION_START_TIME}, {SUBMISSION_END_TIME}, {REVIEW_START_TIME}, {REVIEW_END_TIME}, had the current time, again not taking timezone into a count

- [ ] there are some problems with sender name and email. Sender name does not seem to work in case of automatic emails, only when sending to yourself

- [ ]  tab should be after schedule

- [ ] hint on email body should show the default email

**Comment by davidamebley** [comment]
@samurotko Thank you for the feedback. I will work on the new issues. By the way, how do I get to play with the automatic emails to see how things behave?

**Comment by samurotko** [comment]
@davidamebley you have to create your own even and then register to it. (Registration mail)

By changing status from soft accept to accept you will get acceptance email. By changing status from soft reject to reject you will get rejection email.

**Comment by davidamebley** [comment]
> @davidamebley you have to create your own even and then register to it. (Registration mail)
> 
> By changing status from soft accept to accept you will get acceptance email. By changing status from soft reject to reject you will get rejection email.

Okay. I will do that

**Comment by samurotko** [comment]
> 

Also, check your telegram, I have few question!

**Pull request merged**
